= API

The API is currently at version 1, so all documented paths are currently accessible via

 /api/v1

== Authentication

=== Sign Up
 PUT /auth/signup

Sign Up for the Libs service; Generates and returns a client API key.

[source,javascript]
{
    "username":"librarian",
    "email":"librarian@library.com",
    "password":"encryptedSecret"
}

[source,javascript]
Status: 201 CREATED
{
    "apiKey":"hashedApiKey"
}

=== Login
 POST /auth/login

Log in to the Libs service; Generates a new client API key.

[source,javascript]
{
    "username":"librarian",
    "password":"encryptedsecret"
}

[source,javascript]
Status: 200 OK
{
    "apiKey":"hashedApiKey"
}

== Library
=== Get Libraries
 GET /library/:username

Fetch all existing library.

[source,javascript]
Status: 200 OK
[
    {
        "name": "library1",
        "geoLocation (optional)": "point"
    },
    {
        "name": "library2",
        "geoLocation (optional)": "point"
    }
]

=== Get Library
 GET /library/:username/:library

Fetch an existing library.

[source,javascript]
Status: 200 OK
{
    "geoLocation (optional)": "point"
}

=== Create Library
 PUT /library/:username/:library

Create a new library.

[source,javascript]
{
    "geoLocation (optional)": "point"
}

[source,javascript]
Status: 201 CREATED

=== Update Library
 POST /library/:username/:library

Update the details of an existing library

[source,javascript]
{
    "geoLocation (optional)": "point"
}

[source,javascript]
Status: 200 OK

=== Remove Library
 DELETE /library/:username/:library

Remove an existing library.
[source,javascript]
Status: 200 OK
