= API

The API is currently at version 1, so all documented paths are currently accessible via

 /api/v1

== Authentication

=== Sign Up
 PUT /auth/signup

Sign Up for the Libs service; Generates and returns a client API key.

[source,javascript]
{
    "username":"librarian",
    "email":"librarian@library.com",
    "password":"encryptedSecret"
}

[source,javascript]
Status: 201 CREATED
{
    "apiKey":"hashedApiKey"
}

=== Login
 POST /auth/login

Log in to the Libs service; Generates a new client API key.

[source,javascript]
{
    "username":"librarian",
    "password":"encryptedsecret"
}

[source,javascript]
Status: 200 OK
{
    "apiKey":"hashedApiKey"
}

== Library
=== Get Libraries
 GET /library/:username

Fetch all existing library.

[source,javascript]
Status: 200 OK
[
    {
        "id": "id",
        "name": "library1",
        "geoLocation (optional)": "point"
    },
    {
        "id": "id",
        "name": "library2",
        "geoLocation (optional)": "point"
    }
]

=== Get Library
 GET /library/:user/:library

Fetch an existing library.

[source,javascript]
Status: 200 OK
{
    "id": "id",
    "name": "library",
    "geoLocation (optional)": "point"
}

=== Create Library
 PUT /library/:user/:library

Create a new library.

[source,javascript]
{
    "geoLocation (optional)": "point"
}

[source,javascript]
Status: 201 CREATED
{
    "id": "id"
}

=== Update Library
 POST /library/:user/:library

Update the details of an existing library.

[source,javascript]
{
    "geoLocation (optional)": "point"
}

[source,javascript]
Status: 200 OK

=== Remove Library
 DELETE /library/:user/:library

Remove an existing library.
[source,javascript]
Status: 200 OK

== Book
=== Create Book
 PUT /book

Create a new book.

[source,javascript]
{
    "authors": ["Jim Koogleshreiber", "John Boochmacher"],
    "title": "Necronomicon",
    "isbn (optional)": "978-0380751921",
    "cover": "link/binary"
}

[source,javascript]
Status: 201 CREATED
{
    "id": "id"
}

=== Get Book
 GET /book/:id

Create a new book.

Status: 200 OK
[source,javascript]
{
    "id": "id",
    "authors": ["Jim Koogleshreiber", "John Boochmacher"],
    "title": "Necronomicon",
    "isbn (optional)": "978-0380751921",
    "cover": "link/binary"
}

=== Update Book
 POST /book/:id

Update the information of an existing book.
[source,javascript]
{
    "authors": ["Jim Koogleshreiber", "John Boochmacher"],
    "title": "Necronomicon",
    "isbn (optional)": "978-0380751921",
    "cover": "link/binary"
}

[source,javascript]
Status: 200 OK

=== Remove book
 DELETE /book/:id

Remove an existing book.
[source,javascript]
Status: 200 OK